 CREATE USER HISTORY IDENTIFIED BY HistoryPwd DEFAULT TABLESPACE HISTORYDATA TEMPORARY TABLESPACE TEMP;
 CREATE USER GRIDUSER IDENTIFIED BY GridPwd DEFAULT TABLESPACE GRIDDATA TEMPORARY TABLESPACE TEMP;
 CREATE USER LOGUSER IDENTIFIED BY LogPwd DEFAULT TABLESPACE LOGDATA TEMPORARY TABLESPACE TEMP;
 CREATE USER CONCUSER IDENTIFIED BY ConcPwd DEFAULT TABLESPACE CONCDATA TEMPORARY TABLESPACE TEMP;
 CREATE USER CULOGUSER IDENTIFIED BY LogPwd DEFAULT TABLESPACE LOGDATA TEMPORARY TABLESPACE TEMP;

 grant dba to history;
 grant dba to griduser;
 grant dba to loguser;
 grant dba to concuser;
 grant dba to culoguser;
