 CREATE TABLESPACE HISTORYDATA DATAFILE 'o:\ORADATA\ALGO\HISTORYDATA01.DBF' SIZE 16384M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;
 
 CREATE TABLESPACE HISTORYIDX DATAFILE  'q:\ORADATA\ALGO\HISTORYIDX01.DBF' SIZE 4096M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;
 
 CREATE TABLESPACE GRIDDATA DATAFILE  'o:\ORADATA\ALGO\GRIDDATA01.DBF' SIZE 4096M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;
 
 CREATE TABLESPACE GRIDIDX DATAFILE  'q:\ORADATA\ALGO\GRIDIDX01.DBF' SIZE 2048M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;
 
 CREATE TABLESPACE LOGDATA DATAFILE  'o:\ORADATA\ALGO\LOGDATA01.DBF' SIZE 16384M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;
 ALTER TABLESPACE LOGDATA ADD DATAFILE  'o:\ORADATA\ALGO\LOGDATA02.DBF' SIZE 16384M;

 CREATE TABLESPACE LOGIDX DATAFILE  'q:\ORADATA\ALGO\LOGIDX01.DBF' SIZE 8192M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;

 CREATE TABLESPACE CONCDATA DATAFILE  'o:\ORADATA\ALGO\CONCDATA01.DBF' SIZE 16384M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;
 
 CREATE TABLESPACE CONCIDX DATAFILE  'q:\ORADATA\ALGO\CONCIDX01.DBF' SIZE 8192M
 BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  AUTOALLOCATE  ONLINE PERMANENT  SEGMENT SPACE MANAGEMENT AUTO;

 --CREATE TEMPORARY TABLESPACE TEMP TEMPFILE  'C:\ORACLE\ORADATA\ALGO\TEMP.DBF' SIZE 8192M 
 --BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL  UNIFORM SIZE 1048576;
 